import { useEffect, useRef, useState, type ReactNode } from 'react';
import { motion, MotionConfig } from 'framer-motion';
import { ArrowUpRight, ArrowRight, ArrowUp, Check, ChevronLeft, ChevronRight, Menu, X, Tv, AudioLines, Wrench, ShieldCheck, Headphones, MessageCircle, Phone, Mail, Instagram, MapPin, Plus, Maximize2 } from 'lucide-react';
import { config, whatsappUrl } from './config';
import { services, projects, faqs, maintenance } from './data';
import OrderForm from './OrderForm';
import AudioExperience from './AudioExperience';
import { CinematicHero, InteractiveCursor, ScrollStatement } from './Editorial';
function Logo(){return <a className="brand" href="#inicio" aria-label="ConnectHD, início"><svg viewBox="0 0 33 33" aria-hidden="true"><path d="M5 8v17M12 3v27M19 10v13M26 6v21" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg><span>connect<span>hd</span><small>ÁUDIO & TV</small></span></a>}
function Reveal({children,className=''}:{children:ReactNode,className?:string}){return <motion.div className={className} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.5}}>{children}</motion.div>}
function Modal({children,onClose,label}:{children:ReactNode,onClose:()=>void,label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;d?.close()}},[]);return <dialog ref={ref} className="dialog" aria-label={label} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-inner"><button className="round-button dialog-close" aria-label="Fechar" onClick={onClose}><X size={20}/></button>{children}</div></dialog>}
function Room({size=65,wires=false}:{size?:number,wires?:boolean}){return <div className="room-visual"><div className="slat-wall"/><div className="scaled-tv" style={{width:`${size/98*64}%`}}><div/><small>{size}″</small></div><div className="media-console"/>{wires&&<svg className="wires" viewBox="0 0 600 350" preserveAspectRatio="none"><path d="M280 175v70q0 30 35 15t20 50M300 175v45q-50 25-10 60t-30 40M315 175v85l40 35" fill="none" stroke="#252c28" strokeWidth="4"/></svg>}</div>}
function Planning(){const [tab,setTab]=useState(0),[split,setSplit]=useState(50),[size,setSize]=useState(65),[stage,setStage]=useState(0);return <section className="planning-section section" id="planeje"><div className="wrap"><div className="section-top"><div><span className="overline">CADA ESCOLHA, UM AMBIENTE MELHOR</span><h2>Veja a diferença.<br/><em>Imagine no seu espaço.</em></h2></div><p>Explore o tamanho ideal, o cuidado com os cabos e como funciona nossa manutenção.</p></div><div className="planning-tabs" role="tablist" aria-label="Planeje seu projeto">{['Encontre o tamanho','O cuidado no acabamento','Sua TV, em boas mãos'].map((s,i)=><button role="tab" key={s} id={`plan-tab-${i}`} aria-selected={tab===i} aria-controls="plan-panel" tabIndex={tab===i?0:-1} onClick={()=>setTab(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const n=(tab+(e.key==='ArrowRight'?1:2))%3;setTab(n);document.getElementById(`plan-tab-${n}`)?.focus()}}}>{[<Tv size={18}/>,<ShieldCheck size={18}/>,<Wrench size={18}/>][i]}{s}</button>)}</div><div className="planning-content" role="tabpanel" id="plan-panel" aria-labelledby={`plan-tab-${tab}`}>
{tab===0&&<><Room size={size}/><div className="planning-copy"><span className="overline">PROPORÇÃO FAZ TODA A DIFERENÇA</span><h3>Qual TV combina<br/>com a sua sala?</h3><p>Mova o controle e compare como cada tamanho ocupa o ambiente.</p><label className="size-label" htmlFor="size">Tamanho da TV <strong>{size}″</strong></label><input id="size" aria-label="Tamanho da TV" type="range" min={30} max={98} value={size} onChange={e=>setSize(+e.target.value)}/><div className="range-scale"><span>30 polegadas</span><span>98 polegadas</span></div><div className="planning-tip"><ShieldCheck size={19}/><p>{size>75?'Uma tela grande pede fixação reforçada. Verificamos o peso, o padrão VESA e a estrutura antes de instalar.':'Fixa para um visual discreto, articulada para mais ângulos. A gente ajuda a escolher o suporte adequado.'}</p></div><small>Representação ilustrativa. A escolha final depende das medidas e da estrutura do local.</small></div></>}
{tab===1&&<><div className="comparison"><Room/><div className="before" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}><Room wires/></div><span className="before-label">Antes</span><span className="after-label">Depois</span><div className="compare-handle" style={{left:`${split}%`}}><span>↔</span></div><input type="range" min={0} max={100} value={split} aria-label="Comparar instalação antes e depois" onChange={e=>setSplit(+e.target.value)}/></div><div className="planning-copy"><span className="overline">MENOS FIOS. MAIS AMBIENTE.</span><h3>O que você não vê<br/>também importa.</h3><p>Arraste a divisória. Uma instalação bem pensada valoriza a tela e respeita o restante da sua casa.</p><ul className="check-list"><li><Check/>Cabos organizados</li><li><Check/>Altura e alinhamento precisos</li><li><Check/>Acabamento combinado antes do serviço</li></ul><small>Simulação ilustrativa. A ocultação dos cabos depende da viabilidade do ambiente.</small></div></>}
{tab===2&&<><div className="repair-steps">{maintenance.map(([s],i)=><button className={stage===i?'active':''} aria-pressed={stage===i} onClick={()=>setStage(i)} key={s}><span>0{i+1}</span>{s}<ArrowUpRight size={18}/></button>)}</div><div className="planning-copy" aria-live="polite"><span className="overline">ETAPA 0{stage+1} DE 06</span><h3>{maintenance[stage][0]}</h3><p>{maintenance[stage][1]}</p><button className="inline-link" onClick={()=>setStage((stage+1)%6)}>Próxima etapa <ArrowRight size={18}/></button></div></>}
</div></div></section>}
export default function App(){const [menu,setMenu]=useState(false),[service,setService]=useState(0),[detail,setDetail]=useState<number|null>(null),[filter,setFilter]=useState('Todos'),[photo,setPhoto]=useState<number|null>(null),[privacy,setPrivacy]=useState(false);const visible=projects.filter(p=>filter==='Todos'||p.category===filter);function order(i:number){setService(i);setDetail(null);setTimeout(()=>document.getElementById('pedido')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),20)}function movePhoto(n:number){setPhoto(p=>p===null?null:(p+n+visible.length)%visible.length)}useEffect(()=>{if(photo===null)return;const fn=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')movePhoto(1);if(e.key==='ArrowLeft')movePhoto(-1)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[photo,visible.length]);const nav=[['servicos','Soluções'],['experiencia','Experiência 7.1'],['projetos','Inspirações'],['como-funciona','Como funciona']];return <MotionConfig reducedMotion="user"><InteractiveCursor/><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><div className="top-strip"><div className="wrap"><span><MapPin size={13}/>Atendemos toda a região de São Paulo</span><a href="tel:+5511999076581">Vamos conversar: (11) 99907-6581 <ArrowUpRight size={13}/></a></div></div><header className="site-header"><div className="wrap header-row"><Logo/><nav className={menu?'is-open':''} aria-label="Menu principal">{nav.map(([id,s])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{s}</a>)}</nav><a className="btn btn-dark header-button" href="#pedido">Consultar valores <ArrowUpRight size={17}/></a><button className="menu-button" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main id="conteudo"><CinematicHero/><ScrollStatement/>
<section className="section services-section" id="servicos"><div className="wrap"><Reveal className="section-top"><div><span className="overline">[ 01 — SOLUÇÕES ]</span><h2>O SEU AMBIENTE.<br/><em>EM OUTRO NÍVEL.</em></h2></div><p>Escolha o que seu ambiente precisa.<br/>Nós ajudamos a encontrar o melhor caminho.</p></Reveal><div className="service-grid">{services.map((s,i)=><Reveal key={s.title}><article className="service-card" data-cursor="Ver solução"><div className="service-card-top"><s.icon size={30} strokeWidth={1.35}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.desc}</p><button className="service-detail" aria-label={`Ver detalhes: ${s.title}`} data-cursor="Ver solução" onClick={()=>setDetail(i)}>Ver detalhes <ArrowUpRight size={19}/></button></article></Reveal>)}</div></div></section>
<section className="experience-section" id="experiencia"><div className="wrap"><div className="experience-intro"><span className="overline">APERTE O PLAY. MUDE DE PERSPECTIVA.</span><span>UMA PRÉVIA DO QUE O SOM PODE FAZER.</span></div><AudioExperience onQuote={()=>order(1)}/></div></section>
<section className="section inspirations" id="projetos"><div className="wrap"><div className="section-top"><div><span className="overline">PARA IMAGINAR O SEU</span><h2>Menos equipamentos à vista.<br/><em>Mais espaço para viver.</em></h2></div><div className="project-filters" aria-label="Filtrar inspirações">{['Todos','TV','Home Theater','Áudio'].map(s=><button key={s} onClick={()=>{setFilter(s);setPhoto(null)}} className={filter===s?'active':''} aria-pressed={filter===s}>{s}</button>)}</div></div><div className="project-grid">{visible.map((p,i)=><button className="project" data-cursor="Explorar" key={p.title} onClick={()=>setPhoto(i)}><div className="project-image"><img src={p.image} alt={p.title} loading="lazy" width={900} height={650}/><span><Maximize2 size={18}/></span></div><div className="project-caption"><span className="overline">{p.category}</span><h3>{p.title}<ArrowUpRight size={21}/></h3><p>{p.sub}</p></div></button>)}</div><p className="photo-note">Referências visuais de ambientes. Não representam serviços executados pela ConnectHD.</p></div></section>
<Planning/>
<section className="section process-section" id="como-funciona"><div className="wrap"><div className="section-top"><div><span className="overline">SEM COMPLICAÇÃO</span><h2>Você conta a ideia.<br/><em>A gente cuida do resto.</em></h2></div><a href="#pedido" className="inline-link">Solicitar orçamento <ArrowUpRight size={18}/></a></div><div className="process-grid">{[['Você solicita','Solicite um orçamento aqui ou fale pelo WhatsApp.'],['A gente analisa','Entendemos seu espaço e apresentamos o orçamento.'],['Tudo é instalado','Com técnica, organização e respeito pela sua casa.'],['É só aproveitar','Imagem e som prontos para fazer parte da sua rotina.']].map(([s,p],i)=><Reveal key={s}><span className="process-number">0{i+1}</span><h3>{s}</h3><p>{p}</p></Reveal>)}</div></div></section>
<section className="care-section"><div className="care-image"><img src="/images/audio.webp" alt="Ambiente elegante com sistema de som integrado" loading="lazy" width={1000} height={800}/></div><div className="care-copy"><span className="overline">INSTALAR É SÓ UMA PARTE</span><h2>O seu ambiente<br/><em>merece cuidado.</em></h2><p>Uma boa instalação não termina quando a tela acende. Ela aparece no alinhamento, na organização dos cabos e no jeito de atender.</p><ul><li><span>01</span><div><h3>Precisão em cada instalação</h3><p>Alinhamento a laser e fixação adequada à estrutura.</p></div></li><li><span>02</span><div><h3>Uma solução que faz sentido</h3><p>Seu ambiente, seus equipamentos e sua rotina no centro do projeto.</p></div></li><li><span>03</span><div><h3>Conversa direta, do início ao fim</h3><p>Orientação clara, orçamento alinhado e atenção de verdade.</p></div></li></ul></div></section>
<section className="section order-section" id="pedido"><div className="wrap order-layout"><div className="order-intro"><span className="overline">VAMOS FAZER ACONTECER</span><h2>Seu próximo<br/>bom momento<br/><em>começa aqui.</em></h2><p>Conte o que você precisa para receber um orçamento sob medida. Nós analisamos os detalhes para encontrar a solução certa.</p><div className="contact-person"><span><MessageCircle size={23}/></span><div><strong>Prefere falar com a gente?</strong><a href={whatsappUrl()} target="_blank" rel="noreferrer">(11) 99907-6581 <ArrowUpRight size={16}/></a></div></div><div className="order-area"><MapPin size={19}/><span>Atendimento em toda<br/><strong>a região de São Paulo.</strong></span></div></div><OrderForm service={service} setService={setService}/></div></section>
<section className="section faq-section" id="faq"><div className="wrap faq-layout"><div><span className="overline">BOM SABER ANTES</span><h2>Suas dúvidas,<br/><em>bem resolvidas.</em></h2><a className="inline-link" href={whatsappUrl()} target="_blank" rel="noreferrer">Tem outra pergunta? Fale com a gente <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></div></section>
<section className="closing"><div className="wrap"><div><span className="overline">IMAGEM, SOM E TUDO NO SEU LUGAR.</span><h2>Vamos conectar<br/><em>o seu próximo projeto?</em></h2></div><a className="btn btn-cream" href="#pedido">Solicitar orçamento <ArrowUpRight size={20}/></a></div></section></main>
<footer id="contato"><div className="wrap footer-top"><div><Logo/><p>Tecnologia bem instalada.<br/>Ambiente bem cuidado.</p></div><div><span className="overline">FALE COM A CONNECTHD</span><a href="tel:+5511999076581"><Phone size={16}/>{config.phone}</a><a href={`mailto:${config.email}`}><Mail size={16}/>{config.email}</a><a href={config.instagram} target="_blank" rel="noreferrer"><Instagram size={16}/>@connecthd_</a></div><div><span className="overline">EXPLORE</span><a href="#servicos">Nossas soluções</a><a href="#experiencia">Experiência de áudio</a><a href="#pedido">Solicitar orçamento</a><a href="#faq">Dúvidas frequentes</a></div><div><span className="overline">POR PERTO</span><p>Atendemos toda a<br/>região de São Paulo.</p><a href={whatsappUrl('Olá, ConnectHD! Gostaria de consultar o atendimento na minha cidade.')} target="_blank" rel="noreferrer">Consultar disponibilidade <ArrowUpRight size={16}/></a></div></div><div className="wrap footer-bottom"><span>© 2026 CONNECT HD. Todos os direitos reservados.</span><button onClick={()=>setPrivacy(true)}>Privacidade dos seus dados</button><a href="#inicio">Voltar ao início <ArrowUp size={15}/></a></div></footer><a className="whatsapp-float" href={whatsappUrl()} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp"><MessageCircle size={25}/></a>
{detail!==null&&<Modal label={services[detail].title} onClose={()=>setDetail(null)}><span className="overline">SOLUÇÕES CONNECTHD</span><h2>{services[detail].title}</h2><p>{services[detail].detail}</p><ul className="check-list">{services[detail].items.map(s=><li key={s}><Check size={18}/>{s}</li>)}</ul><button className="btn btn-dark" onClick={()=>order(detail)}>Solicitar este serviço <ArrowUpRight size={18}/></button></Modal>}
{photo!==null&&<Modal label={visible[photo].title} onClose={()=>setPhoto(null)}><img className="lightbox-image" src={visible[photo].image} alt={visible[photo].title}/><h3>{visible[photo].title}</h3><p>Imagem de inspiração · {visible[photo].category}</p><button className="btn btn-dark" onClick={()=>{const category=visible[photo].category;setPhoto(null);order(category==='TV'?0:1)}}>Quero uma solução assim <ArrowUpRight size={18}/></button><div className="lightbox-actions"><button className="round-button" aria-label="Imagem anterior" onClick={()=>movePhoto(-1)}><ChevronLeft/></button><span>{photo+1} / {visible.length}</span><button className="round-button" aria-label="Próxima imagem" onClick={()=>movePhoto(1)}><ChevronRight/></button></div></Modal>}
{privacy&&<Modal label="Privacidade dos seus dados" onClose={()=>setPrivacy(false)}><span className="overline">SEUS DADOS</span><h2>Uma conversa com confiança.</h2><p>Ao registrar um pedido, seu nome, telefone, localização informada e detalhes do serviço são armazenados pela ConnectHD para analisar e responder à solicitação. Não informe dados de cartão, documentos ou informações sensíveis nas observações.</p><p>O botão de WhatsApp abre uma mensagem no serviço externo; você revisa o conteúdo antes de enviar. Para solicitar acesso, correção ou exclusão de seus dados, entre em contato pelo e-mail <a href={`mailto:${config.email}`}>{config.email}</a>.</p><p>Pedidos são armazenados no banco de dados do servidor. Não são exibidos publicamente.</p></Modal>}
</MotionConfig>}
