import { Tv, AudioLines, Wrench, Cable } from 'lucide-react';
export const services = [
 {title:'Instalação de TV',tag:'NO LUGAR CERTO. DO JEITO CERTO.',icon:Tv,desc:'Sua TV perfeitamente alinhada. Seu ambiente ainda mais bonito.',items:['TVs de 30″ a 98″+ em parede ou painel','Alinhamento preciso a laser e fixação segura','Suportes fixos, articulados e inclináveis','Organização e ocultação de cabos conforme o ambiente'],detail:'Avaliamos a superfície, o peso e o padrão de fixação da sua TV para indicar a solução adequada. Planejamos a altura e o ângulo de visão, protegemos o ambiente e finalizamos com testes de segurança e funcionamento.'},
 {title:'Áudio & Home Theater',tag:'SINTA CADA DETALHE.',icon:AudioLines,desc:'Som que envolve. Tecnologia que se integra à sua casa.',items:['Home theater 5.1 e 7.1','Caixas de teto e áudio ambiente','Projetos residenciais e comerciais','Posicionamento e configuração do sistema'],detail:'Desenhamos a solução de áudio a partir do seu espaço, dos equipamentos e da experiência que você procura. A posição das caixas, os caminhos dos cabos e a integração com a TV são avaliados para um resultado equilibrado.'},
 {title:'Manutenção de TV',tag:'SUA TV EM BOAS MÃOS.',icon:Wrench,desc:'Da coleta à devolução, cuidado em todas as etapas.',items:['Coleta no local mediante agendamento','Avaliação técnica do equipamento','Orçamento antes da execução','Devolução com testes de funcionamento'],detail:'Conte o que aconteceu com sua TV e informe o modelo. Confirmamos a disponibilidade de coleta para sua região, avaliamos o equipamento e apresentamos o orçamento. O reparo é realizado somente após sua aprovação.'},
 {title:'Produtos & Acessórios',tag:'TUDO CONECTADO.',icon:Cable,desc:'A escolha certa para completar o seu projeto.',items:['TVs e equipamentos de áudio','Suportes compatíveis com sua TV','Cabos e conexões para cada uso','Orientação sobre compatibilidade e disponibilidade'],detail:'Ajudamos você a escolher os equipamentos e acessórios adequados ao projeto. Consulte modelos, condições e disponibilidade diretamente com a equipe antes de comprar.'}
];
export const nav = [['inicio','Início'],['servicos','Serviços'],['projetos','Projetos'],['como-funciona','Como funciona'],['diferenciais','Diferenciais'],['faq','FAQ'],['contato','Contato']];
export const maintenance = [ ['Solicitação','Conte o sintoma, a marca e o modelo da sua TV. Nossa equipe orienta os próximos passos.'],['Coleta','Combinamos a retirada do equipamento e confirmamos a disponibilidade para sua região.'],['Avaliação','A equipe realiza a análise técnica para identificar o problema e as possibilidades de reparo.'],['Orçamento','Você recebe os valores e as condições para decidir. O serviço só começa após sua aprovação.'],['Manutenção','Executamos o reparo aprovado com os cuidados adequados ao seu equipamento.'],['Devolução','Após os testes de funcionamento, agendamos a devolução da sua TV.'] ];
export const projects = [ {title:'TV instalada com acabamento limpo',category:'TV',image:'/images/living.webp',sub:'Mais espaço para o que importa.'},{title:'Cinema e som dentro de casa',category:'Home Theater',image:'/images/theater.webp',sub:'Uma experiência que envolve.'},{title:'Áudio integrado ao ambiente',category:'Áudio',image:'/images/audio.webp',sub:'Presença no som. Discrição no espaço.'} ];
export const faqs = [ ['Quais tamanhos de TV vocês instalam?','Atendemos TVs de 30″ a 98″ e modelos maiores mediante avaliação. A instalação depende do peso, do padrão VESA, da resistência da parede ou painel e do suporte escolhido. Envie o modelo e uma foto do local para receber uma orientação.'],['Vocês fornecem o suporte?','Podemos orientar e fornecer suportes conforme a disponibilidade e as necessidades do projeto. Trabalhamos com soluções fixas, inclináveis e articuladas. Se você já tem um suporte, verificamos a compatibilidade e as condições de uso.'],['É possível esconder os cabos?','Sim, avaliamos alternativas como passagens existentes, painéis e canaletas. A possibilidade de embutir a fiação depende da estrutura e das condições do ambiente. A solução e qualquer intervenção necessária são combinadas no orçamento.'],['Vocês montam home theater?','Sim. Planejamos a instalação e a configuração do home theater conforme o ambiente e os equipamentos, incluindo posicionamento das caixas, conexões com a TV e ajustes do sistema. Podemos trabalhar com equipamentos existentes ou orientar uma nova composição.'],['Instalam caixas de som no teto?','Sim. Instalamos caixas de teto em projetos residenciais e comerciais, após verificar o forro, os pontos de fixação, o cabeamento e a compatibilidade do sistema de amplificação. O projeto busca distribuir o som de forma equilibrada.'],['Qual a diferença entre 5.1 e 7.1?','Um sistema 5.1 utiliza cinco canais principais e um canal de graves, normalmente reproduzido por um subwoofer. O 7.1 acrescenta dois canais principais para ampliar a sensação espacial. A escolha depende do espaço, do posicionamento disponível e da compatibilidade dos equipamentos.'],['Minha TV quebrou. Vocês buscam?','Oferecemos coleta no local mediante agendamento e confirmação da área atendida. Informe o modelo e o defeito percebido. Explicaremos as condições de retirada e avaliação antes de combinar a coleta. O reparo depende da análise técnica e da aprovação do orçamento.'],['Como funciona o orçamento?','Envie o serviço desejado, sua localização e informações sobre os equipamentos. Fotos do ambiente ajudam na análise. Dependendo do serviço, pode ser necessária uma avaliação técnica. Valores, prazos e eventuais custos de visita ou coleta são informados antes da contratação.'] ];

