import { useEffect, useRef, useState } from 'react';
import { motion, useMotionValue, useReducedMotion, useScroll, useSpring, useTransform, type MotionValue } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Headphones, MessageCircle } from 'lucide-react';
import { whatsappUrl } from './config';

export function InteractiveCursor(){const x=useMotionValue(-100),y=useMotionValue(-100),sx=useSpring(x,{stiffness:400,damping:35}),sy=useSpring(y,{stiffness:400,damping:35});const [label,setLabel]=useState('');const reduce=useReducedMotion();useEffect(()=>{if(reduce||!matchMedia('(pointer:fine)').matches)return;const move=(e:PointerEvent)=>{x.set(e.clientX);y.set(e.clientY);const el=(e.target as Element).closest('[data-cursor]') as HTMLElement|null;setLabel(el?.dataset.cursor||'')};const leave=()=>setLabel('');document.addEventListener('pointermove',move);document.addEventListener('pointerleave',leave);return()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerleave',leave)}},[reduce]);return <motion.div className="editorial-cursor" aria-hidden="true" style={{x:sx,y:sy,opacity:label?1:0,scale:label?1:.7}}><span>{label}</span><ArrowUpRight size={16}/></motion.div>}
export function CinematicHero(){const ref=useRef<HTMLDivElement>(null),reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const scale=useTransform(scrollYProgress,[0,.5,1],[.91,1,1.06]);return <section className="cinematic-hero" id="inicio"><div className="wrap cinema-heading"><div className="cinema-meta"><span>ÁUDIO, TV & AMBIENTES</span><span>SÃO PAULO — BR</span></div><h1 aria-label="ConnectHD"><span>CONNECT</span><span className="hd-letter">HD</span><span className="title-period" aria-hidden="true">↗</span></h1><div className="cinema-summary"><span>TECNOLOGIA BEM INSTALADA.<br/>AMBIENTE BEM CUIDADO.</span><div><p>A TV no lugar certo. O som que envolve.<br/>Sua casa, do jeito que você imaginou.</p><div className="cinema-actions"><a href="#pedido" className="btn btn-dark" data-cursor="Começar">Fazer meu pedido <ArrowUpRight size={18}/></a><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle size={16}/>WhatsApp</a></div></div><a href="#cena" className="discover" aria-label="Explorar o site"><ArrowDown size={22}/></a></div></div><div className="cinema-scene" id="cena" ref={ref}><motion.img style={{scale:reduce?1:scale}} src="/images/living.webp" alt="Sala contemporânea com TV na parede e instalação organizada" width={1920} height={1576} fetchPriority="high"/><div className="scene-shade"/><div className="scene-caption"><span className="overline">O ESPAÇO É SEU. A EXPERIÊNCIA TAMBÉM.</span><h2>ASSISTA.<br/><span>SINTA.</span><br/>VIVA.</h2><a className="scene-audio-link" data-cursor="Ouvir" href="#experiencia"><Headphones size={21}/><span>COLOQUE OS FONES<br/><strong>Entre na experiência 7.1</strong></span><ArrowUpRight size={25}/></a></div><span className="scene-credit">AMBIENTE DE INSPIRAÇÃO · CONNECTHD</span></div></section>}
function Word({word,index,total,progress}:{word:string,index:number,total:number,progress:MotionValue<number>}){const opacity=useTransform(progress,[index/total*.75,(index+1)/total*.75],[.18,1]);return <motion.span style={{opacity}}>{word} </motion.span>}
export function ScrollStatement(){const ref=useRef<HTMLElement>(null),reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start 85%','end 45%']});const words='A BOA TECNOLOGIA NÃO OCUPA O SEU ESPAÇO. ELA TRANSFORMA O JEITO DE VIVER NELE.'.split(' ');return <section ref={ref} className="scroll-statement wrap"><span className="overline">[ A NOSSA ESSÊNCIA ]</span><p aria-label={words.join(' ')}>{words.map((word,i)=>reduce?<span key={i}>{word} </span>:<Word key={i} word={word} index={i} total={words.length} progress={scrollYProgress}/>)}</p><div><span>Instalação de TV · Home theater · Áudio ambiente · Manutenção</span><a href="#servicos">Conheça as soluções <ArrowDown size={16}/></a></div></section>}
