import { useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, LoaderCircle, MessageCircle, ShieldCheck, Copy } from 'lucide-react';
import { services } from './data';
import { whatsappUrl } from './config';
import { quoteMessage } from './quoteMessage';
type Details={problem:string,size:string,place:string,name:string,phone:string,city:string,notes:string,consent:boolean,website:string};
const initial:Details={problem:'Não liga',size:'Não sei / não se aplica',place:'Outro / a definir',name:'',phone:'',city:'',notes:'',consent:false,website:''};
export default function OrderForm({service,setService}:{service:number,setService:(n:number)=>void}){
  const [step,setStep]=useState(1),[data,setData]=useState<Details>(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState(''),[copied,setCopied]=useState(false);
  const attempt=useRef({key:crypto.randomUUID(),payload:''});
  function change<K extends keyof Details>(key:K,value:Details[K]){setData(d=>({...d,[key]:value}));setError('')}
  function message(){return quoteMessage({...data,service:services[service].title,reference})}
  async function submit(e:FormEvent){e.preventDefault();if(document.documentElement.dataset.preview==='true'){setError('Esta é uma prévia visual. Para registrar pedidos no banco, execute INICIAR.cmd no projeto completo. O WhatsApp continua disponível.');return}if(busy)return;setError('');const phone=data.phone.replace(/\D/g,'');if(!/^(?:55)?\d{10,11}$/.test(phone)){setError('Confira o telefone: precisamos do número com DDD.');return}setBusy(true);const payload=JSON.stringify({...data,service:services[service].title});if(attempt.current.payload&&attempt.current.payload!==payload)attempt.current.key=crypto.randomUUID();attempt.current.payload=payload;
    try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':attempt.current.key},body:payload,signal:AbortSignal.timeout(15000)});let result;try{result=await response.json()}catch{throw new Error('O serviço de pedidos está indisponível. Tente novamente ou continue pelo WhatsApp.')}if(!response.ok)throw new Error(result.error||'Não foi possível salvar o pedido.');if(!result.reference)throw new Error('Não recebemos a confirmação. Tente novamente.');setReference(result.reference)}catch(e){setError(e instanceof Error?(e.name==='TimeoutError'?'A confirmação demorou mais que o esperado. Tente novamente; seu pedido não será duplicado.':e.message):'Falha de conexão. Tente novamente.')}finally{setBusy(false)}
  }
  if(reference)return <div className="order-success" role="status"><span className="success-icon"><CheckCircle2/></span><span className="overline">PEDIDO REGISTRADO</span><h3>Pronto, {data.name.split(' ')[0]}.<br/>Agora é com a gente.</h3><p>Seu pedido foi salvo. A ConnectHD poderá entrar em contato pelo telefone informado para analisar o projeto e combinar o orçamento.</p><div className="reference"><span>SEU PROTOCOLO</span><strong>{reference}</strong><button aria-label="Copiar protocolo" onClick={async()=>{try{await navigator.clipboard.writeText(reference);setCopied(true)}catch{setCopied(false)}}}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><p className="order-note">O registro não confirma agendamento, preço ou contratação.</p><a className="btn btn-dark" href={whatsappUrl(message())} target="_blank" rel="noreferrer"><MessageCircle size={18}/>Conversar sobre meu pedido</a><button className="quiet-button" onClick={()=>{setReference('');setData(initial);setStep(1);attempt.current={key:crypto.randomUUID(),payload:''}}}>Fazer outro pedido</button></div>;
  return <div className="order-panel"><div className="order-steps">{['Serviço','Seu projeto','Contato'].map((s,i)=><button key={s} disabled={i+1>step||busy} onClick={()=>setStep(i+1)} className={step===i+1?'current':step>i+1?'done':''}><span>{step>i+1?<Check size={13}/>:i+1}</span>{s}</button>)}</div><div className="order-panel-content">
  {step===1&&<><span className="overline">PRIMEIRO, O ESSENCIAL</span><h3>Como podemos ajudar?</h3><p>Escolha o serviço que mais combina com o que você precisa.</p><div className="order-service-list">{services.map((s,i)=><button key={s.title} className={service===i?'selected':''} aria-pressed={service===i} onClick={()=>setService(i)}><s.icon size={23}/><span><strong>{s.title}</strong><small>{['Instalação segura e acabamento cuidadoso','Som ambiente, caixas de teto e cinema em casa','Avaliação, coleta e reparo da sua TV','Equipamentos e acessórios para seu espaço'][i]}</small></span><span className="radio-mark">{service===i&&<span/>}</span></button>)}</div><button className="btn btn-dark wide" onClick={()=>setStep(2)}>Continuar <ArrowRight size={18}/></button></>}
  {step===2&&<><span className="overline">OS DETALHES FAZEM A DIFERENÇA</span><h3>Conte um pouco do projeto.</h3><p>Não precisa saber tudo agora. A gente ajuda você a decidir.</p>{service===2&&<label>Qual é o problema da TV?<select value={data.problem} onChange={e=>change('problem',e.target.value)}>{['Não liga','Liga, mas não aparece imagem','Sem som','Imagem com linhas ou manchas','Tela quebrada','Desliga sozinha','Outro problema'].map(p=><option key={p}>{p}</option>)}</select></label>}<fieldset><legend>Tamanho da TV</legend><div className="choice-grid">{['30–50″','51–65″','66–75″','76–98″+','Não sei / não se aplica'].map(s=><button key={s} onClick={()=>change('size',s)} className={data.size===s?'chosen':''} aria-pressed={data.size===s}>{s}</button>)}</div></fieldset><fieldset><legend>Onde será o serviço?</legend><div className="choice-grid places">{['Parede','Painel','Outro / a definir'].map(s=><button key={s} onClick={()=>change('place',s)} className={data.place===s?'chosen':''} aria-pressed={data.place===s}>{s}</button>)}</div></fieldset><label>O que você tem em mente? <span>(opcional)</span><textarea value={data.notes} onChange={e=>change('notes',e.target.value)} maxLength={2000} rows={3} placeholder="Modelo da TV, ideias para o som, defeito ou detalhes do ambiente…"/></label><div className="wizard-actions"><button className="back-button" onClick={()=>setStep(1)}><ArrowLeft size={17}/>Voltar</button><button className="btn btn-dark" onClick={()=>setStep(3)}>Continuar <ArrowRight size={18}/></button></div></>}
  {step===3&&<form onSubmit={submit}><span className="overline">ÚLTIMO PASSO</span><h3>Vamos tirar a ideia do papel.</h3><p>Informe seus dados para registrarmos o pedido e falarmos com você.</p><div className="selected-summary"><Check size={16}/>{services[service].title}<button type="button" onClick={()=>setStep(1)}>Alterar</button></div><div className="form-row"><label>Seu nome<input name="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="Como podemos chamar você?" value={data.name} onChange={e=>change('name',e.target.value)}/></label><label>Celular com DDD<input name="phone" required type="tel" autoComplete="tel" maxLength={25} placeholder="(11) 99999-9999" value={data.phone} onChange={e=>change('phone',e.target.value)}/></label></div><label>Bairro e cidade<input name="city" required minLength={3} maxLength={120} autoComplete="address-level2" placeholder="Ex.: Moema, São Paulo" value={data.city} onChange={e=>change('city',e.target.value)}/></label><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>change('website',e.target.value)}/></label></div><label className="consent"><input type="checkbox" required checked={data.consent} onChange={e=>change('consent',e.target.checked)}/><span>Autorizo a ConnectHD a usar estes dados para responder ao meu pedido. Eles serão salvos para este atendimento.</span></label>{error&&<div role="alert" className="form-error">{error}</div>}<div className="wizard-actions"><button type="button" className="back-button" disabled={busy} onClick={()=>setStep(2)}><ArrowLeft size={17}/>Voltar</button><button type="submit" className="btn btn-dark" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<CheckCircle2 size={18}/>} {busy?'Registrando…':'Registrar meu pedido'}</button></div><p className="order-note"><ShieldCheck size={15}/>Sem pagamento agora. Orçamento após análise.</p></form>}
  </div><div className="order-whatsapp"><span>Prefere uma conversa?</span><a href={whatsappUrl(message())} target="_blank" rel="noreferrer"><MessageCircle size={17}/>Continuar pelo WhatsApp <ArrowRight size={15}/></a></div></div>
}
